#!/usr/bin/env node
// Bundles every src/demo/*.js file (as raw source text) into
// src/common/demos.gen.js so pages can list and run them.
//
// The aiot toolkit has no raw-source loader for .js, so we generate a
// plain module at build time instead. Run via `npm run gen-demos`
// (hooked into prestart/prebuild/prerelease).

const fs = require("fs")
const path = require("path")

const root = path.resolve(__dirname, "..")
const demoDir = path.join(root, "src", "demo")
const outFile = path.join(root, "src", "common", "demos.gen.js")

function main() {
  if (!fs.existsSync(demoDir)) {
    fs.mkdirSync(demoDir, {recursive: true})
  }

  const files = fs
    .readdirSync(demoDir)
    .filter((f) => f.endsWith(".js"))
    .sort()

  const demos = files.map((file) => ({
    name: file.replace(/\.js$/, ""),
    file,
    code: fs.readFileSync(path.join(demoDir, file), "utf8")
  }))

  const body = [
    "// AUTO-GENERATED by scripts/gen-demos.js -- do not edit.",
    `// Source: src/demo/*.js (${demos.length} file${demos.length === 1 ? "" : "s"})`,
    "",
    `export default ${JSON.stringify(demos, null, 2)}`,
    ""
  ].join("\n")

  fs.mkdirSync(path.dirname(outFile), {recursive: true})
  fs.writeFileSync(outFile, body)
  console.log(`[gen-demos] ${demos.length} demo(s) -> ${path.relative(root, outFile)}`)
  demos.forEach((d) => console.log(`  - ${d.file} (${d.code.length} bytes)`))
}

main()
